import * as fs from 'fs';
import * as path from 'path';
import { BaseIntegration } from '../BaseIntegration';
import { IEditorIntegration, IntegrationMetadata, ArchitectureRules, EditorContext } from '../interfaces';

/**
 * Cursor editor integration.
 *
 * Reads and writes Cursor's rule files (.cursor/rules or legacy .cursorrules).
 * Each Cursor project has its own isolated secret namespace for API keys —
 * this mirrors how Cursor itself stores keys per-workspace.
 *
 * Cursor rules format: plain Markdown with optional YAML front-matter.
 */
export class CursorIntegration extends BaseIntegration implements IEditorIntegration {
  readonly metadata: IntegrationMetadata = {
    id: 'cursor',
    name: 'Cursor Editor Integration',
    category: 'editor',
    description: 'Bidirectional architecture rules sync with Cursor (.cursor/rules)',
    requiredSecrets: [],  // optional: cursor API key for model access
  };

  protected async onInitialize(): Promise<void> { /* no remote connection */ }

  // ── IEditorIntegration ────────────────────────────────────────────────────

  async readContext(workspacePath: string): Promise<EditorContext> {
    const content = this.readRulesFile(workspacePath);
    if (!content) { return {}; }

    return {
      rawContent: content,
      rules: this.parseRules(content),
      projectName: path.basename(workspacePath),
    };
  }

  async writeRules(workspacePath: string, rules: ArchitectureRules): Promise<void> {
    const content = this.buildRulesContent(rules);
    const rulesDir = path.join(workspacePath, '.cursor');
    if (!fs.existsSync(rulesDir)) { fs.mkdirSync(rulesDir, { recursive: true }); }
    fs.writeFileSync(path.join(rulesDir, 'rules'), content, 'utf8');
  }

  buildPromptContext(ctx: EditorContext): string {
    if (!ctx.rules) { return ''; }
    const lines: string[] = [
      `## Cursor Project Architecture Rules`,
      `Style: ${ctx.rules.style}`,
      `Language: ${ctx.rules.language}`,
    ];
    if (ctx.rules.framework) { lines.push(`Framework: ${ctx.rules.framework}`); }
    if (ctx.rules.layers?.length) { lines.push(`Layers: ${ctx.rules.layers.join(' → ')}`); }
    if (ctx.rules.conventions?.length) {
      lines.push('Conventions:');
      ctx.rules.conventions.forEach(c => lines.push(`  - ${c}`));
    }
    if (ctx.rules.forbiddenPatterns?.length) {
      lines.push('Forbidden:');
      ctx.rules.forbiddenPatterns.forEach(p => lines.push(`  - ${p}`));
    }
    return lines.join('\n');
  }

  // ── Private helpers ───────────────────────────────────────────────────────

  private readRulesFile(workspacePath: string): string | null {
    const candidates = [
      path.join(workspacePath, '.cursor', 'rules'),
      path.join(workspacePath, '.cursorrules'),
    ];
    for (const candidate of candidates) {
      if (fs.existsSync(candidate)) {
        return fs.readFileSync(candidate, 'utf8');
      }
    }
    return null;
  }

  private parseRules(content: string): ArchitectureRules {
    const rules: ArchitectureRules = { style: 'custom', language: 'TypeScript' };

    const langMatch = content.match(/language[:\s]+(\w[\w+#-]*)/i);
    if (langMatch) { rules.language = langMatch[1]; }

    const styleMatch = content.match(/style[:\s]+(layered|hexagonal|clean|microservices|custom)/i);
    if (styleMatch) { rules.style = styleMatch[1] as ArchitectureRules['style']; }

    const fwMatch = content.match(/framework[:\s]+([^\n]+)/i);
    if (fwMatch) { rules.framework = fwMatch[1].trim(); }

    const layerMatch = content.match(/layers?[:\s]+([^\n]+)/i);
    if (layerMatch) { rules.layers = layerMatch[1].split(/[,→>|]+/).map(s => s.trim()).filter(Boolean); }

    const conventionSection = content.match(/conventions?:([^#]*)/i);
    if (conventionSection) {
      rules.conventions = conventionSection[1].split('\n')
        .map(l => l.replace(/^[-*]\s*/, '').trim())
        .filter(Boolean);
    }

    return rules;
  }

  private buildRulesContent(rules: ArchitectureRules): string {
    const lines: string[] = [
      '# Architecture Rules — generated by Alpaquitay AI',
      '',
      `language: ${rules.language}`,
      `style: ${rules.style}`,
    ];

    if (rules.framework) { lines.push(`framework: ${rules.framework}`); }

    if (rules.layers?.length) {
      lines.push('', `## Layers`, `layers: ${rules.layers.join(' → ')}`);
    }

    if (rules.conventions?.length) {
      lines.push('', '## Conventions');
      rules.conventions.forEach(c => lines.push(`- ${c}`));
    }

    if (rules.forbiddenPatterns?.length) {
      lines.push('', '## Forbidden Patterns');
      rules.forbiddenPatterns.forEach(p => lines.push(`- ${p}`));
    }

    if (rules.customRules?.length) {
      lines.push('', '## Custom Rules');
      rules.customRules.forEach(r => lines.push(`- ${r}`));
    }

    lines.push('', SOLID_FOOTER);
    return lines.join('\n');
  }
}

const SOLID_FOOTER = `
## SOLID Principles (always enforced)
- Single Responsibility: one class/module = one reason to change
- Open/Closed: extend via new classes, not by modifying existing ones
- Liskov Substitution: subtypes must honour the base contract
- Interface Segregation: prefer focused interfaces over fat ones
- Dependency Inversion: depend on abstractions, inject concretions
`.trim();
